# Generated by Django 4.1.2 on 2022-11-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0002_musician_genre_musician_instrument_musician_ratings_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="musician",
            name="user_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
