# Generated by Django 4.1.2 on 2022-11-06 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_musician_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="musician",
            name="views",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name="ProfileViews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("IPAddres", models.GenericIPAddressField(default="45.243.82.169")),
                (
                    "musician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.musician",
                    ),
                ),
            ],
        ),
    ]
