# Generated by Django 4.1.2 on 2022-11-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_musician_views_profileviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="muser",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="muser",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="muser",
            name="dp",
            field=models.ImageField(
                default="uphotos/dummydp.png", upload_to="uphotos/"
            ),
        ),
        migrations.AddField(
            model_name="muser",
            name="full_address",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="muser",
            name="full_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="muser",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="muser",
            name="pin_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="muser",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
