# Generated by Django 3.2.4 on 2022-12-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_files_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='Trailer_Song_Link',
            field=models.FileField(blank=True, upload_to='trailersongs/'),
        ),
    ]
